### ISSUE TITLE
Property drawer parsing edge cases

### ISSUE THREAD

**Issue by calmofthestorm** [PoiScript/orgize#9]
Hi,

I believe I have identified a bug in parsing properties drawer. I'm not sure exactly what it is, but I have several bad strings which when parsed and written out are very different. It may be related to properties which have no value, as per https://orgmode.org/worg/dev/org-syntax.html#Node_Properties

https://gist.github.com/calmofthestorm/08d0afeef571312d778958a5a5c2ad69

I have also observed that just `:DRAWER:` or `:END:` occurring in a node body will result in an `:END:` being added. This is still incorrect in my opinion -- a property drawer that cannot be properly parsed should be treated as body text -- but is much more understandable, especially since Org mode can identify and suggest fixing unclosed drawers.

This is a drawback of Org's permissive structure where every string is a valid Org mode file.

**Comment by PoiScript** [comment]
I apologize for not answering sooner! I just got a new macbook and it's harder than I thought to setup a rust environment on it. =)

This bug's caused by [these lines](https://github.com/PoiScript/orgize/blob/2ec3f6982aaac94ba22bc021ce1bd0109630cb96/src/elements/drawer.rs#L67-L69) where the parser doesn't check if `:END:` is present. I'm working for a fix right now.

**Comment by PoiScript** [comment]
This bug is fixed and out with v0.8.1 now.

**Comment by calmofthestorm** [comment]
Thanks!
